config/routes.rb
Railsdemo::Application.routes.draw do
  get "sessions/new"

  get "users/new"

  match 'pricing' => 'welcome#pricing'

  resources :sites do
    resources :snapshots do
      resources :assets
    end
  end

  get "signup" => "users#new", :as => "signup"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :users
  resources :sessions

  root :to => 'welcome#index'

end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :url, :snapshots_attributes

  validates :url, :format => URI::regexp(%w(http https))

  validates_uniqueness_of :url

  has_many :snapshots

  belongs_to :user
end

app/controllers/sites_controller.rb
require 'uri/http'

class SitesController < ApplicationController
  before_filter :auth_user

  def index
  	@site = Site.new
  	@site_list = @current_user.sites.all
  end

  def create
  	# Set the values from the form
    @site = Site.new params[:site]

    # Associate the site with the logged in user
    @site.user_id = @current_user.id

    # Parse the URL
    uri = URI.parse(@site.url)

    # Set the specifics about this URL
    @site.is_ssl = false unless uri.scheme.to_s == 'https'
    @site.domain = uri.host.to_s
    @site.uri = uri.path.to_s
    @site.uri << '?' + uri.query.to_s unless uri.query == nil
    @site.uri << '#' + uri.fragment.to_s unless uri.fragment == nil

    # Save the site
  	if @site.save
  		redirect_to sites_path, :flash => { :notice => "Successfully added #{@site.url}." }
  	else
  		redirect_to :back, :flash => { :error => 'Error adding URL.' }
  	end

  	#render :text => params.inspect
  end

  def show
    # Find the site in the DB
    @site = Site.find(params[:id])

    # Ensure the site is owned by this user
    if @site.user_id != @current_user.id
      redirect_to :back, :flash => { :error => 'You are not the site owner' }
    end
  end

  def destroy
    # Find the site in the DB
    @site = Site.find(params[:id])

    # Ensure the site is owned by this user
    if @site.user_id != @current_user.id
      redirect_to :back, :flash => { :error => 'You are not the site owner' }
    end

    # Remove the site from the DB
    if @site.destroy
      redirect_to sites_path, :flash => { :notice => 'Successfully deleted site.' }
    else
      redirect_to site_path(@site), :flash => { :error => 'Error deleting URL' }
    end
  end

  private

  def auth_user
    #Need to make this more global

    # Require the user to be logged in
    @current_user ||= User.find(session[:user_id]) if session[:user_id]

    if !@current_user
      redirect_to root_url, :flash => {:error => 'You must be logged in to see the site list.' }
    end
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/index.html.erb
<% content_for :title, "Site List" %>
<div class="row">
	<div class="twelve columns">
		<ul class="breadcrumbs">
		  <li><%= link_to 'Home', root_url %></li>
		  <li class="current"><%= link_to 'Site List', sites_path %></li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="eight columns">
		<h3>Site List</h3>
		<table class="twelve">
		  <thead>
		    <tr>
		      <th>URL</th>
		      <th>Title</th>
		      <th>Snapshots</th>
		      <th>% Change</th>
		    </tr>
		  </thead>
		  <tbody>
		  	<% for site in @site_list %>
					<tr>
			      <td><%= link_to site.url, site_snapshots_path(site) %></td>
			      <td><%= if site.snapshots.size > 0
			      					site.snapshots.last.title
			      				else
			      					'NA'
			      				end %></td>
			      <td><%= site.snapshots.size %></td>
			      <td>0%</td>
			    </tr>
				<% end %>
		  </tbody>
		</table>
	</div>

	<div class="four columns">
		<h3>Add Site</h3>
		<%= form_for @site do |f| %>
			<%= f.label :url %>
			<%= f.text_field :url %>
			<%= f.submit "Add Site" %>
		<% end %>
	</div>
</div>

app/views/sites/show.html.erb
<% content_for :title, @site.url %>
<div class="row">
	<div class="twelve columns">
		<h3><%= @site.url %> <small><span class="alert label radius"><%= link_to 'Delete', @site, :method => 'delete', :confirm => 'Are you sure?' %></span></small></h3>
	</div>
</div>